---
ID: "3576314a-a47a-4365-83ad-95d412835d41"
Parent: "c6f9cacb-e8a0-45a2-bdf3-72e69e50a575"
Template: "c6f9cacb-e8a0-45a2-bdf3-72e69e50a575"
Path: /sitecore/templates/Project/Common/Parameters/ParametersTemplate_HasContainerWithBackground/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150921T024007Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        extranet\Anonymous
