---
ID: "03167897-2a83-4ab4-a655-5b295322f17c"
Parent: "684ed0dd-8f16-4761-bc6f-62cbc4116d31"
Template: "29d4b405-39eb-487d-9d6b-3f8467ab167d"
Path: /sitecore/content/Habitat/Global/Teasers/AboutUs/ValuesTeaser
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170331T064427Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170331T064427Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
