---
ID: "73c59589-2bc6-4200-a631-7bac9d33ae64"
Parent: "0a165175-80f7-4d74-abfe-1e8371df0761"
Template: "8ee208f9-a6a6-41e2-88a0-c188737a178c"
Path: /sitecore/content/Habitat/NewHome/Services
DB: master
SharedFields:
- ID: "5585a30d-b115-4753-93ce-422c3455deb2"
  Hint: ShowInNavigation
  Type: Checkbox
  Value: 1
- ID: "68016087-aa00-45d6-922a-678475c50d4a"
  Hint: ShowChildren
  Type: Checkbox
  Value: 0
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 275
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1b483e91-d8c4-4d19-ba03-462074b55936"
      Hint: NavigationTitle
      Value: Services
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170314T114200Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "9492e0bb-9df9-46e7-8188-ec795c4ade44"
      Hint: Image
      Value: |
        <image mediaid="{7C358D66-E47C-4C44-A4D1-2125E531F801}" />
    - ID: "ac3fd4db-8266-476d-9635-67814d91e901"
      Hint: Summary
      Value: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut<br />et dolore magna aliqua. Ut enim ad minim veniam
    - ID: "c30a013f-3cc8-4961-9837-1c483277084a"
      Hint: Title
      Value: Services
    - ID: "ca0479ce-0bfe-4522-83de-ba688b380a78"
      Hint: BrowserTitle
      Value: Products
    - ID: "d74f396d-5c5e-4916-bd0a-bfd58b6b1967"
      Hint: Body
      Value: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
