---
ID: "ed7f1efa-7fa5-46c4-9385-010b94516169"
Parent: "ea13174a-b43e-4f68-b474-b41188771a9e"
Template: "920a1781-559f-4e1c-bb2e-6b9a2113fe6b"
Path: /sitecore/content/Habitat/Global/Media/Products
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170408T072249Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
