---
ID: "d1a7eefd-9342-459a-b281-b40da160d340"
Parent: "b6f000a5-e43f-4899-84d5-7108279a6dc3"
Template: "b6f000a5-e43f-4899-84d5-7108279a6dc3"
Path: /sitecore/templates/Project/Common/Content Types/Products/ProductCategorySelector/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170406T072825Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
