---
ID: "1db546c5-f33e-4ce6-b2e5-c6d2b15b07f7"
Parent: "20dd980b-cd20-45f7-987b-8d3c91b30d6d"
Template: "390333c8-751b-4332-84a3-6360b969a19f"
Path: /sitecore/content/Habitat/Global/Links/Footer Menu/Footer Bottom Menu/Products
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 150
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1b483e91-d8c4-4d19-ba03-462074b55936"
      Hint: NavigationTitle
      Value: Products
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170320T092205Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "fe71c30e-f07d-4052-8594-c3028cd76e1f"
      Hint: Link
      Value: |
        <link text="" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{752B9A88-691D-4BF2-98A5-4A10B2E388EB}" />
