---
ID: "89bca7db-a08a-4528-9fc4-fb0c29a649c3"
Parent: "fbd84d73-fce8-4064-962c-3af7ea0263f9"
Template: "fbd84d73-fce8-4064-962c-3af7ea0263f9"
Path: /sitecore/templates/Project/Common/Content Types/Product Category Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170321T082857Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
