---
ID: "601975a8-23f5-4f86-98e8-be01b1f3bd9c"
Parent: "bb4ecaf5-be3b-4be7-b6bc-6bcc0b5bb77f"
Template: "98e4bdc6-9b43-4eb2-baa3-d4303c35852e"
Path: /sitecore/content/Habitat/Global/Dictionary/Products
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170407T112611Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
