---
ID: "d5830167-eac2-415e-8c95-250ffc9bf445"
Parent: "94a8c8e9-690b-4e65-98e7-f95800222767"
Template: "94a8c8e9-690b-4e65-98e7-f95800222767"
Path: /sitecore/templates/Project/Habitat/Page Types/Article/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {94A8C8E9-690B-4E65-98E7-F95800222767}
    {8FF3D369-A508-4D2F-84A5-9B6C6BF5E537}
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{ED043C36-CD48-4EDF-A288-EC404EE1CD42}">
        <r
          id="{E7AE3F87-CF66-40F2-A9F5-33ECF08BC777}"
          ph="head"
          uid="{E6CA18D8-321D-4105-9C38-0622E94BE400}" />
        <r
          id="{BA10AC38-FDAD-47FE-B038-5F322F0678A1}"
          ph="header-top"
          uid="{F963AA98-4957-45B5-95CD-B61C242063E1}" />
        <r
          ds="{DC450599-7C22-4D86-A901-CC8EEC8992C9}"
          id="{29A50BE2-7FD9-4C2C-9641-35806DD2C21F}"
          ph="left-header-top"
          uid="{05FFB7B4-377C-4C00-9520-0ED7735CADCA}" />
        <r
          ds="{DC450599-7C22-4D86-A901-CC8EEC8992C9}"
          id="{69B9C355-004B-4268-BB1E-2F725B8752B7}"
          par=""
          ph="center-header-top"
          uid="{630F4515-1F19-49A8-B986-D46ADD5CE024}" />
        <r
          id="{8C3A2CFC-18FB-4BF5-8584-50EA88978ED6}"
          ph="right-header-top"
          uid="{69DE8A76-E455-4505-95A3-6D7FAA25C088}" />
        <r
          id="{E26A158B-FA1E-4E9B-8622-E4458243FF46}"
          ph="navbar"
          uid="{07C9FE71-A5E2-4E5F-B276-5F2B73481D44}" />
        <r
          id="{A47C8288-7D4C-45FF-B75F-4AEDBF58A02D}"
          ph="navbar-left"
          uid="{7BD25BD6-C6C4-4FBE-9828-D29A39A2FEC9}" />
        <r
          id="{53B085DB-6824-4941-9F28-9011CB151832}"
          ph="navbar-center"
          uid="{FBDB4313-35B5-4C26-A586-17F48FD2DC41}" />
        <r
          id="{28BD7068-7FF6-4CE6-98E6-85CFE9967E14}"
          ph="navbar-right"
          uid="{75551DEC-A457-43A3-B76F-91742B5DDE93}" />
        <r
          id="{359A65BB-0A2C-44E5-8C34-DF3ACDBB42A7}"
          ph="page-layout"
          uid="{1DF746C3-2D29-43E6-9DE2-05622DED6F97}" />
        <r
          id="{E6BA23C6-08F7-43D0-BE00-BB2129D6F288}"
          ph="page-header"
          uid="{20E3883C-C16D-41D7-B5D3-C4AC60D8386D}" />
        <r
          ds=""
          id="{EADA94FA-315F-4DF2-AC49-13346DFDAF12}"
          par="Background&amp;Background Image&amp;ContainerIsFluid&amp;UseStaticPlaceholderNames=1"
          ph="page-layout"
          uid="{66422117-69C1-4B62-9323-482F16C4F244}" />
        <r
          ds=""
          id="{3F7AD288-FA57-441F-AD79-CA60DC0C0A8D}"
          par=""
          ph="/page-layout/col-narrow-1"
          uid="{A85893F9-5DF5-4C28-AC0F-67AD85D29661}" />
        <r
          id="{695CEE74-D8F4-481D-B813-237050809290}"
          ph="/page-layout/col-wide-1"
          uid="{3CDF4DD8-28A4-4185-8C09-A73CAA4633F7}" />
        <r
          id="{914673DC-FC44-4660-B6EB-FF421FAAC2F9}"
          ph="/page-layout/col-wide-1"
          uid="{565F9960-4E47-4DA4-9406-0A29DD09911F}" />
        <r
          id="{299FD8EA-2CFD-4A69-9CA4-7EA24CD34A46}"
          ph="footer"
          uid="{E2040FB7-4151-456D-9315-5973E4EB4D9D}" />
        <r
          ds=""
          id="{D201A487-5099-48A1-8189-55944F70C6CB}"
          par="Background=%7B6A2EED97-1642-43A3-827E-427D6013FDBE%7D&amp;Background Image&amp;ContainerIsFluid&amp;UseStaticPlaceholderNames=1"
          ph="/footer/section"
          uid="{025588CB-DFC0-4B02-8223-0015C525AE52}" />
        <r
          ds=""
          id="{DE648E12-A568-4919-802E-A688EBC9B9F3}"
          par="Background&amp;Background Image&amp;ContainerIsFluid&amp;UseStaticPlaceholderNames=1"
          ph="/footer/section/section"
          uid="{36853A12-FFAB-4A8F-AB84-E858B8B5594C}" />
        <r
          ds="{FB1E4810-6D89-4F1E-A47B-70478FE32DA7}"
          id="{F366FBA9-EF26-4007-988A-63CB64649C46}"
          par=""
          ph="/footer/section/section/col-narrow-1"
          uid="{0E0C6DCA-1A29-4975-84D7-E99498A64A72}" />
        <r
          ds="{390056FB-8813-483A-B82A-DB6843768726}"
          id="{F366FBA9-EF26-4007-988A-63CB64649C46}"
          par=""
          ph="/footer/section/section/col-narrow-2"
          uid="{0E0C6DCA-1A29-4975-84D7-E99498A64A72}" />
        <r
          ds="{7A02D67F-9B00-47D7-8CD1-79A8B95EC4D3}"
          id="{F366FBA9-EF26-4007-988A-63CB64649C46}"
          par=""
          ph="/footer/section/section/col-narrow-3"
          uid="{47F5A079-6F63-4219-BC45-1A221B200906}" />
        <r
          ds="{B4D87E66-D2C5-4C06-8F9A-08AEAF38055A}"
          id="{F366FBA9-EF26-4007-988A-63CB64649C46}"
          par=""
          ph="/footer/section/section/col-narrow-4"
          uid="{84124EE2-E678-4144-8316-0D6874866604}" />
        <r
          ds=""
          id="{1B92270B-EC01-4939-B579-0ADFEB758A95}"
          par="Background=%7B2E6F5F32-6948-44CE-93E9-1ABAAD9C5917%7D&amp;Background Image&amp;ContainerIsFluid&amp;UseStaticPlaceholderNames=1"
          ph="postfooter"
          uid="{90A858AD-16B0-4D3D-94AB-B4B4DBF5C6AF}" />
        <r
          ds=""
          id="{7DAE9F23-890F-4E06-99A7-CCEDB74D3D8E}"
          par=""
          ph="/footer/postfooter/col-wide-1"
          uid="{A3BAD4D4-8E21-4B30-8C4C-B04163653D62}" />
        <r
          ds="{20DD980B-CD20-45F7-987B-8D3C91B30D6D}"
          id="{F366FBA9-EF26-4007-988A-63CB64649C46}"
          par=""
          ph="/footer/postfooter/col-wide-2"
          uid="{3FDD01BF-80A8-47D8-A565-D69EF17BBBEE}" />
        <r
          id="{CBEA7B7B-EEF5-46CE-83C4-AB8E7371CE7A}"
          ph="virtualassistance"
          uid="{5E0632C1-BA30-49E5-A673-C2143529B5DB}" />
        <r
          ds=""
          id="{0AD8EC59-33EC-4103-AAD4-F3A49BFDB92C}"
          par="Background&amp;Background Image&amp;ContainerIsFluid&amp;UseStaticPlaceholderNames=1"
          ph="page-layout"
          uid="{89D6842C-19FB-4470-8263-AD10FABF561D}" />
        <r
          ds=""
          id="{4ACD4C20-28D1-46F7-8FBA-A35778937BD1}"
          par="Background&amp;Background Image&amp;ContainerIsFluid&amp;UseStaticPlaceholderNames=1"
          ph="/page-layout/col-huge"
          uid="{67911409-22D4-49FB-9D67-8B1328BA0596}" />
        <r
          ds="{F79DB404-F073-4B41-B4EB-0F4D46D775F3}"
          id="{F940BB36-C78C-46B8-8778-BC49348AA58A}"
          par="Background"
          ph="/page-layout/col-huge/col-wide-1"
          uid="{134F4086-8F02-4F12-825E-FF96EC885863}" />
        <r
          ds="{1B3AA94B-7180-4030-90DE-2469C22A8D9C}"
          id="{D0CAC0A2-DB40-424A-88E0-EBC5D3F6DBF1}"
          par="Background"
          ph="/page-layout/col-huge/col-narrow-1"
          uid="{B50087F3-2ECC-4349-AACA-C26C868404F2}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1b483e91-d8c4-4d19-ba03-462074b55936"
      Hint: NavigationTitle
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150824T175451Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "9492e0bb-9df9-46e7-8188-ec795c4ade44"
      Hint: Image
      Value: |
        <image mediaid="{88032F9C-B464-44CB-B76D-513D60B9C127}" />
    - ID: "c30a013f-3cc8-4961-9837-1c483277084a"
      Hint: Title
      Value: $name
    - ID: "ca0479ce-0bfe-4522-83de-ba688b380a78"
      Hint: BrowserTitle
      Value: $name
